[FEAT] Adds home page
daviddubliakov/opentech-web pull request #1
Opened 2023-09-22 12:25 UTC by ww-side

2023-09-22 13:08 UTC, heilrake commented on src/components/common/ReviewsCarousel/index.tsx
> +import { FC } from 'react';
Подобавляй для //Core та // Components та  // Utils в усі файли
в //Core повинні бути  бібліотеки 
в // Components => Components ,
 // Utils все що не відносить до Core  та Components 
![image](https://github.com/daviddubliakov/opentech-web/assets/58284931/6931ac29-37a3-4e24-a797-100855b4452a)

2023-09-22 13:08 UTC, heilrake commented on src/components/layouts/SectionLayout/index.tsx
> +      className={`px-[100px] ${isPadding ? 'pt-16' : ''} ${
Винеси це краще перед return , щоб було className= {ClassNames} , так як в Button ти зробив

2023-09-22 13:08 UTC, heilrake commented on src/components/ui/RadioButton/index.tsx
> +      className={`${
Винеси це краще перед return , щоб було className= {ClassNames} , так як в Button ти зробив

2023-09-22 13:08 UTC, heilrake commented on src/components/common/AppParticles/index.tsx
> +  const particlesLoaded = useCallback(
Чи потрібен цей particlesLoaded  взагалі?

2023-09-22 13:08 UTC, heilrake commented on src/components/ui/RadioButton/index.tsx
> +        checked={name === value}
Виглядає странно, тут точно так треба?

2023-09-22 13:59 UTC, ww-side commented on src/app/layout.tsx
>    description: 'Generated by create next app',
changed

2023-09-22 13:59 UTC, ww-side commented on src/components/common/AppParticles/index.tsx
> +      console.log(container);
removed

2023-09-22 14:01 UTC, ww-side commented on src/components/common/Form/formValidationSchema.ts
> +  email: z.string().email().optional(),
removed except service

2023-09-22 14:01 UTC, ww-side commented on src/components/common/Form/formValidationSchema.ts
> +  name: z
removed

2023-09-22 14:02 UTC, ww-side commented on src/components/common/Form/index.tsx
> +    console.log(req);
removed

2023-09-22 14:02 UTC, ww-side commented on src/components/common/ReviewsCarousel/index.tsx
> +import { FC } from 'react';
added

2023-09-22 14:02 UTC, ww-side commented on src/components/layouts/SectionLayout/index.tsx
> +      className={`px-[100px] ${isPadding ? 'pt-16' : ''} ${
changed

2023-09-22 14:03 UTC, ww-side commented on src/components/ui/RadioButton/index.tsx
> +      className={`${
changed

2023-09-22 14:03 UTC, ww-side commented on src/components/common/AppParticles/index.tsx
> +  const particlesLoaded = useCallback(
removed

2023-09-22 14:03 UTC, ww-side commented on src/components/ui/RadioButton/index.tsx
> +        checked={name === value}
removed

2023-09-22 14:04 UTC, ww-side commented on src/components/common/Form/formValidationSchema.ts
changed

2023-09-22 14:44 UTC, daviddubliakov requested changes

2023-09-22 14:44 UTC, daviddubliakov commented on package.json
>      "@types/node": "20.6.2",
Типи винести в devDependencies

2023-09-22 14:44 UTC, daviddubliakov commented on src/app/layout.tsx
> +  title: 'OpenTech',
Стоврити папку `constants` і винести в окремий файл

2023-09-22 14:44 UTC, daviddubliakov commented on src/app/page.tsx
> +import ServicesCarousel from '@/components/common/ServicesCarousel';
у common та ui компонентів створити index.ts і експортувати все звідти

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/AppParticles/index.tsx
> +'use client';
навіщо тут use client;

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/ReviewsCarousel/ReviewCard/index.tsx
> +      <section className="mt-7">{review}</section>
треба інший тег замість section

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/ReviewsCarousel/index.tsx
> +          key={id()}
зазавичай прийнято писати uuid()

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/ReviewsCarousel/reviews.ts
> +export const reviews = [
перенести в `src/data`

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/Menu/routes.ts
> +export const routes = [
перенести в `src/data`

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/ServicesCarousel/services.ts
> +export const services = [
перенести в `src/data`

2023-09-22 14:44 UTC, daviddubliakov commented on src/components/common/ServicesCarousel/index.tsx
> +          key={id()}
uuid()

2023-09-25 10:30 UTC, ww-side commented on package.json
>      "@types/node": "20.6.2",
виніс

2023-09-25 10:31 UTC, ww-side commented on src/app/page.tsx
> +import ServicesCarousel from '@/components/common/ServicesCarousel';
створив та експортував

2023-09-25 10:31 UTC, ww-side commented on src/components/common/AppParticles/index.tsx
> +'use client';
тому що в Particles використовуються класові компоненти

2023-09-25 10:32 UTC, ww-side commented on src/components/common/CaseList/index.tsx
> +          imgRoute="/img/cases/case.png"
змінив imgRoute на caseName, прокидується назва кейсу та підставляється у роут вже у компоненті

2023-09-25 10:32 UTC, ww-side commented on src/components/common/ReviewsCarousel/index.tsx
> +          key={id()}
змінив

2023-09-25 10:32 UTC, ww-side commented on src/components/common/ReviewsCarousel/reviews.ts
> +export const reviews = [
переніс

2023-09-25 10:32 UTC, ww-side commented on src/components/common/Menu/routes.ts
> +export const routes = [
переніс

2023-09-25 10:32 UTC, ww-side commented on src/components/common/ServicesCarousel/services.ts
> +export const services = [
переніс

2023-09-25 10:33 UTC, ww-side commented on src/components/common/ServicesCarousel/index.tsx
> +          key={id()}
змінив

2023-09-25 11:49 UTC, daviddubliakov approved these changes

2023-09-25 11:50 UTC, merged