[FEAT] Add portfolio page
daviddubliakov/opentech-web pull request #2
Opened 2023-09-28 07:09 UTC by ww-side

2023-09-28 07:48 UTC, heilrake commented on src/components/common/Header/index.tsx
> +      <Link href="/">
Додай href="/" як home в book

2023-09-28 07:48 UTC, heilrake commented on src/components/common/PortfolioCases/PortfolioCard/index.tsx
> +        {viewCaseDetails ? (
Тут тернарний оператор не треба

2023-09-28 07:48 UTC, heilrake commented on src/components/ui/Text/index.tsx
> +    <Element className={TextTag[Element] + ' ' + className}>{children}</Element>
Якщо тобі треба enum чисто для того щоб додати якийсь стіля  то вже краще пропсом прокинути

2023-09-28 07:48 UTC, heilrake commented on src/data/book.ts
> +];
Можеш home ( " / ") сюди додати

2023-09-28 07:48 UTC, heilrake commented on src/data/portfolioCategories.ts
> +  'All works' = 'All works',
Зліва "" не треба ставити для enum  `all = 'All works', web = 'Web', `

2023-09-28 07:48 UTC, heilrake commented on src/types/portfolioCaseType.ts
> +  category: keyof typeof PortfolioCategories;
Щоб не писати  ` keyof typeof PortfolioCategories;`  ти можеш зробити окремий тип для  enum  на основі того ж enum або просто зробити так: `category: PortfolioCategories; `

2023-09-28 08:23 UTC, daviddubliakov requested changes

2023-09-28 08:23 UTC, daviddubliakov commented on src/app/portfolio/page.tsx
> +export default function Portfolio() {
через arrow function

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/common/Form/index.tsx
> +            key={uuid()}
uuid треба писати одразу в data, а тут просто юзати з formService.id

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/common/PortfolioCases/PortfolioCard/index.tsx
> +// Utils
Defenitions

2023-09-28 08:23 UTC, daviddubliakov commented on src/types/portfolioCaseType.ts
> +// Utils
просто файл portfolio.ts

2023-09-28 08:23 UTC, daviddubliakov commented on src/types/technologyType.ts
> +export type TechnologyType = {
файл має бути просто technology

2023-09-28 08:23 UTC, daviddubliakov commented on src/data/ourServices.ts
> +    routeImg: '/img/our-services/frontend.svg',
не потребен роут на картинку. Лише назви

2023-09-28 08:23 UTC, daviddubliakov commented on src/constants/metadata.ts
> +  title: 'OpenTech | Portfolio',
Просто Portflio

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/ui/index.ts
> +export { Text } from '@/components/ui/Text';
реекспорт з індекса має бути всюди де ти використовуєш ui

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/ui/Chip/index.tsx
> +      <Icon icon={icon} propsIcon={{ color: `${iconColor}`, size: 24 }} />
color та size мають прокидать як окремі пропси propsIcon непотрібен

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/ui/Button/index.tsx
> +import { className } from 'postcss-selector-parser';
Core

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/ui/Button/index.tsx
>  // Utils
Components

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/common/PortfolioCases/index.tsx
> +            key={uuid()}
uuid на етапі ствоерння данних

2023-09-28 08:23 UTC, daviddubliakov commented on src/components/common/PortfolioCases/index.tsx
> +            key={uuid()}
uuid на етапі ствоерння данних

2023-09-28 08:26 UTC, ww-side commented on src/components/common/Header/index.tsx
> +      <Link href="/">
вирішили, що не потрібно змінювати

2023-09-28 08:26 UTC, ww-side commented on src/data/book.ts
> +];
вирішили, що не потрібно змінювати

2023-09-28 08:27 UTC, ww-side commented on src/components/common/PortfolioCases/PortfolioCard/index.tsx
> +        {viewCaseDetails ? (
замінив

2023-09-28 08:27 UTC, ww-side commented on src/components/ui/Text/index.tsx
> +    <Element className={TextTag[Element] + ' ' + className}>{children}</Element>
виправив

2023-09-28 08:27 UTC, ww-side commented on src/data/portfolioCategories.ts
> +  'All works' = 'All works',
виправив

2023-09-28 08:27 UTC, ww-side commented on src/types/portfolioCaseType.ts
> +  category: keyof typeof PortfolioCategories;
змінив

2023-09-28 11:05 UTC, ww-side commented on src/app/portfolio/page.tsx
> +export default function Portfolio() {
змінив

2023-09-28 11:05 UTC, ww-side commented on src/components/common/Form/index.tsx
> +            key={uuid()}
замінив

2023-09-28 11:05 UTC, ww-side commented on src/components/common/PortfolioCases/PortfolioCard/index.tsx
> +// Utils
виправив

2023-09-28 11:08 UTC, ww-side commented on src/types/portfolioCaseType.ts
> +// Utils
перейменував

2023-09-28 11:08 UTC, ww-side commented on src/types/technologyType.ts
> +export type TechnologyType = {
перейменував

2023-09-28 11:08 UTC, ww-side commented on src/data/ourServices.ts
> +    routeImg: '/img/our-services/frontend.svg',
виправив

2023-09-28 11:09 UTC, ww-side commented on src/constants/metadata.ts
> +  title: 'OpenTech | Portfolio',
виправив

2023-09-28 11:09 UTC, ww-side commented on src/components/ui/Chip/index.tsx
> +      <Icon icon={icon} propsIcon={{ color: `${iconColor}`, size: 24 }} />
виправив

2023-09-28 11:09 UTC, ww-side commented on src/components/ui/Button/index.tsx
> +import { className } from 'postcss-selector-parser';
виправив

2023-09-28 11:09 UTC, ww-side commented on src/components/ui/Button/index.tsx
>  // Utils
виправив

2023-09-28 11:09 UTC, ww-side commented on src/components/common/PortfolioCases/index.tsx
> +            key={uuid()}
виправив

2023-09-28 11:09 UTC, ww-side commented on src/components/common/PortfolioCases/index.tsx
> +            key={uuid()}
виправив

2023-09-28 19:10 UTC, heilrake requested changes

2023-09-28 19:10 UTC, heilrake commented on src/components/common/PortfolioCases/index.tsx
> +  const [category, setCategory] = useState<string>('All works');
Якщо примітивні типи `number, string , boolean ... ` то можеш явно не типізувати, за тебе це зробить ts. Але якщо хочеш то  можеш ставити

2023-09-28 19:10 UTC, heilrake commented on src/components/common/PortfolioCases/index.tsx
> +  const portfolioCategories = [
Я б це виніс кудись в data

2023-10-02 06:27 UTC, ww-side commented on src/components/common/PortfolioCases/index.tsx
> +  const portfolioCategories = [
виніс

2023-10-02 09:40 UTC, daviddubliakov approved these changes

2023-10-02 09:43 UTC, heilrake approved these changes

2023-10-02 09:50 UTC, merged