[FIX] Home page
daviddubliakov/opentech-web pull request #6
Opened 2023-10-05 08:01 UTC by ww-side

- Змінив висоту зображення в меню на 100%
- Змінив пошту в меню, прибрав соціальні мережі в меню та замінив їх на пошту та телефон
- Змінив лого у хедері
- Задізейблив виділення картинки та добавив стрілки для слайдерів our services та reviews, зробив анімацію повільніше
- Порефакторив форму: emailjs та відправка форми
- Додав анімацію для форми та кейсів
- В футері змінив контакти та додав перехід на портфоліо
- Додав анімацію для картинок у меню

2023-10-05 13:14 UTC, heilrake commented on src/components/common/Form/index.tsx
> +                wrapperClass=""
Може wrapperStyle wrapperClass прибрати? Чи так і треба щоб вони нічого не приймали?

2023-10-05 13:18 UTC, daviddubliakov requested changes

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/AppCarousel/index.tsx
> +      className={`cursor-grabbing py-14 ${className}`}
classNames

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/Form/index.tsx
>  import 'dotenv/config';
ці імпорти мають бути вкінці

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/Form/index.tsx
> +    emailjs
Треба створити окремий для цього email.js service

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/Form/index.tsx
> +        inView
classnames

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/HighlightedCases/CaseCard/index.tsx
> +        inView ? `${animation} opacity-100` : 'opacity-0'
classNames

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/common/Menu/index.tsx
> +import 'animate.css';
import in the end

2023-10-05 13:18 UTC, daviddubliakov commented on src/components/ui/Arrow/index.tsx
> +  const position = template === 'right' ? 'right-0' : 'left-0';
classNames

2023-10-06 09:52 UTC, ww-side commented on src/components/common/Form/index.tsx
> +                wrapperClass=""
Прибрав

2023-10-06 09:52 UTC, ww-side commented on src/components/common/AppCarousel/index.tsx
> +      className={`cursor-grabbing py-14 ${className}`}
Додав

2023-10-06 09:52 UTC, ww-side commented on src/components/common/Form/index.tsx
>  import 'dotenv/config';
Додав

2023-10-06 09:52 UTC, ww-side commented on src/components/common/Form/index.tsx
> +      service: 'Front-End development',
Додав

2023-10-06 09:52 UTC, ww-side commented on src/components/common/Form/index.tsx
> +    emailjs
Додав

2023-10-06 09:53 UTC, ww-side commented on src/components/common/Form/index.tsx
> +        inView
Додав

2023-10-06 09:53 UTC, ww-side commented on src/components/common/HighlightedCases/CaseCard/index.tsx
> +  const animation =
Додав

2023-10-06 09:53 UTC, ww-side commented on src/components/common/HighlightedCases/CaseCard/index.tsx
> +        inView ? `${animation} opacity-100` : 'opacity-0'
Додав

2023-10-06 09:53 UTC, ww-side commented on src/components/common/Menu/index.tsx
> +import 'animate.css';
Додав

2023-10-06 09:53 UTC, ww-side commented on src/components/common/ServicesCarousel/index.tsx
> +import { Arrow } from '@/components/ui';
змінив

2023-10-06 09:53 UTC, ww-side commented on src/components/ui/Arrow/index.tsx
> +  const position = template === 'right' ? 'right-0' : 'left-0';
Додав

2023-10-06 09:58 UTC, heilrake commented on src/components/common/ServicesCarousel/index.tsx
> +import { AiOutlineArrowLeft, AiOutlineArrowRight } from 'react-icons/ai';
to components

2023-10-06 09:58 UTC, heilrake commented on src/components/ui/Arrow/index.tsx
> +import classNames from 'classnames';
import cx from 'classnames'

2023-10-06 10:36 UTC, ww-side commented on src/components/common/ServicesCarousel/index.tsx
> +import { AiOutlineArrowLeft, AiOutlineArrowRight } from 'react-icons/ai';
Посортував

2023-10-06 10:36 UTC, ww-side commented on src/components/ui/Arrow/index.tsx
> +import classNames from 'classnames';
Перейменував

2023-10-06 11:25 UTC, heilrake approved these changes

2023-10-06 11:26 UTC, daviddubliakov approved these changes

2023-10-06 11:26 UTC, merged